INSERT INTO users (id, username, password) VALUES (default, 'admin', '1234');

INSERT INTO resources (INSERT INTO resources (title, file_url, category) VALUES

              ('actividad 10 ', '', 'exercises'),
              ('video 4', '', 'tutorials'),
              ('Introducción a JavaScript', './uploads/intro.pdf', 'documentation'),
              ('Código sostenible', './uploads/codigosostenible.pdf', 'documentation'),
              ('Funciones', './uploads/FuncionesJS.pdf', 'documentation'),
              ('DOM', './uploads/DOM.pdf', 'documentation'),
              ('Eventos', './uploads/Eventos.pdf', 'documentation'),
              ('AJAX', './uploads/AJAX.pdf', 'documentation'),
              ('JSON', './uploads/JSON.pdf', 'documentation'),
              ('NodeJS', './uploads/NodeJS.pdf', 'documentation'),
              ('Express', './uploads/Express.pdf', 'documentation'),
              ('MongoDB', './uploads/MongoDB.pdf', 'documentation'),
              ('Mongoose', './uploads/Mongoose.pdf', 'documentation'),
              ('React', './uploads/React.pdf', 'documentation'),
              ('Redux', './uploads/Redux.pdf', 'documentation'),
              ('React Native', './uploads/ReactNative.pdf', 'documentation'),
              ('Angular', './uploads/Angular.pdf', 'documentation'),
              ('Vue', './uploads/Vue.pdf', 'documentation'),
              ('Svelte', './uploads/Svelte.pdf', 'documentation'),
              ('WebPack', './uploads/WebPack.pdf', 'documentation'),
              ('Babel', './uploads/Babel.pdf', 'documentation'),
              ('TypeScript', './uploads/TypeScript.pdf', 'documentation'),
              ('Jest', './uploads/Jest.pdf', 'documentation'),
              ('Mocha', './uploads/Mocha.pdf', 'documentation'),
              ('Chai', './uploads/Chai.pdf', 'documentation'),
              ('Cypress', './uploads/Cypress.pdf', 'documentation'),
              ('Jasmine', './uploads/Jasmine.pdf', 'documentation'),
              ('Karma', './uploads/Karma.pdf', 'documentation'),
              ('Protractor', './uploads/Protractor.pdf', 'documentation'),
              ('Selenium', './uploads/Selenium.pdf', 'documentation'),
              ('Docker', './uploads/Docker.pdf', 'documentation'),
              ('Kubernetes', './uploads/Kubernetes.pdf', 'documentation'),
              ('Jenkins', './uploads/Jenkins.pdf', 'documentation'),
              ('Git', './uploads/Git.pdf', 'documentation'),
              ('GitHub', './uploads/GitHub.pdf', 'documentation'),
              ('GitLab', './uploads/GitLab.pdf', 'documentation'),
              ('BitBucket', './uploads/BitBucket.pdf', 'documentation'),
              ('Heroku', './uploads/Heroku.pdf', 'documentation'),
              ('Netlify', './uploads/Netlify.pdf', 'documentation'),
              ('Vercel', './uploads/Vercel.pdf', 'documentation'),
              ('AWS', './uploads/AWS.pdf', 'documentation')); 

